### ISSUE TITLE
Make installable via luarocks

### ISSUE THREAD

**Issue by FourierTransformer** [teal-language/teal-language-server#26]
With the switch to using the tree-sitter for parsing, the tree-sitter grammar (`teal.so`) needs to be installed on the user's machine to enable tree-sitter parsing. To enable this, I'm planning to try the following:

- [x] Create [tree-sitter-cli](https://github.com/FourierTransformer/tree-sitter-cli) to allow installing tree-sitter CLI via LuaRocks
- [x] Install tree-sitter-teal's grammar via [tree-sitter-teal](https://luarocks.org/modules/neorocks/tree-sitter-teal)
- [x] ~~Try to switch to [lua-tree-sitter](https://github.com/xcb-xwii/lua-tree-sitter)~~
  - Includes [tree-sitter lib](https://github.com/tree-sitter/tree-sitter/tree/master/lib) in the source, so we don't have to try and include that as well.
  - Decided to not go this way in the end.
- [x] Bundle `ltreesitter` and the `tree-sitter` lib together.
- [x] Ideally write unit tests before doing this to ensure all functionality that works with [ltreesitter](https://github.com/euclidianAce/ltreesitter) works with lua-tree-sitter. (I think it should)
  - Should be able to load the grammar installed via the neorocks module
- [x] Update rockspec with all the changes.
  -  waiting on new luarocks-build-treesitter-parser for now
- [x] Test tree-sitter cli without node and just a JSON file
- [x] See if the LuaRocks module for tree-sitter-cli can be made to work on LuaRocks < 3.10.0

This address the major concern from #25

**Comment by FourierTransformer** [comment]
I got `tree-sitter-cli` up and running via LuaRocks and tried installing the `teal.so` grammar via `tree-sitter-teal` and it seemed to all install just fine! 

I'll probably do some testing on loading `parsers/teal.so`.

**Comment by FourierTransformer** [comment]
While the cli can now be installed via LuaRocks, using `tree-sitter-teal` still requires `node` to be installed to do the `teal.so` generation. There are some options in https://github.com/nvim-neorocks/luarocks-build-treesitter-parser that would build from the json file instead, but I'm not sure if that still requires node or has any drawbacks. Might need to investigate further.

**Comment by FourierTransformer** [comment]
I gave the old "college try" at switching to `lua-tree-sitter`. It didn't have the same cursor implementation, and I wasn't quite willing to switch everything over to queries or to nodes. 

I also attempted to get LuaRocks to build the tree-sitter lib for `ltreesitter` and install it, but it would require either root privs to install the header/library in the right place or setting environment variables when doing the dependency installation (which would end up being a user action since it can't be done in a rockspec file).

At this point I'm leaning towards bundling `ltreesitter` and the `tree-sitter` library together. I got that working in a POC and will continue working that direction in the next few days.

**Comment by FourierTransformer** [comment]
So it turns out `tree-sitter` cli _can_ run the `build` command to build a grammar from a JSON file without node. Node is only needed for the `generate` command. I'll either see if we can update the tree-sitter-teal package to use the JSON file, or see if they're willing to put in a fallback to use it if Node is not installed, but the JSON file is present.

As far as installing `tree-sitter-cli` on LuaRocks versions < 3.10.0, it will _install_ just fine with 3.8.0, but seemingly not if it's a LuaRocks tree specified via the commandline. Again, this was fixed in 3.10.0+. so I'm not sure if it's worth chasing.

**Comment by FourierTransformer** [comment]
Alrighty I have two PRs out there, one of which would allow us to install without Node on the system:
- https://github.com/nvim-neorocks/luarocks-build-treesitter-parser/pull/40

and the other which bundles the tree-sitter library with ltreesitter (and we/the world would not need `ltreesitter-ts` any longer):
- https://github.com/euclidianAce/ltreesitter/pull/30

I think when the luarocks-build-treesitter-parser PR is complete with a new version, we can close this issue out! (for ltreesitter, there is currently a workaround in place)

**Comment by FourierTransformer** [comment]
While both got merged, I think we'll have to specify `luarocks-build-treesitter-parser==6.0.0` , since that didn't get updated with the latest [tree-sitter-teal](https://luarocks.org/modules/neorocks/tree-sitter-teal)

Afterwards, I'll probably test some of the luarocks install concerns brought up in #37 and #39.

**Comment by ildar** [comment]
I don't fully understand but what's the status of this?

> Alrighty I have two PRs out there, one of which would allow us to install without Node on the system:
>     * [feat!: try and build with grammar.json if node is not available nvim-neorocks/luarocks-build-treesitter-parser#40](https://github.com/nvim-neorocks/luarocks-build-treesitter-parser/pull/40)

This one is merged.

> and the other which bundles the tree-sitter library with ltreesitter (and we/the world would not need `ltreesitter-ts` any longer):
>     * [Add tree sitter library as submodule euclidianAce/ltreesitter#30](https://github.com/euclidianAce/ltreesitter/pull/30)

also merged.

> I think when the luarocks-build-treesitter-parser PR is complete with a new version, we can close this issue out! (for ltreesitter, there is currently a workaround in place)

I've just got the `ltreesitter` (version 0.0.7 just in case) built normally with system t-s library and all worked fine. Does t-l-s really need that clumsy `ltreesitter-ts` (anymore) ?

**Comment by FourierTransformer** [comment]
> I don't fully understand but what's the status of this?

It's complete in the sense that we got it installing more reliably with just LuaRocks, which was a struggle after integrating tree-sitter, hence why this issues is now closed.

> Does t-l-s really need that clumsy ltreesitter-ts (anymore) ?

`ltreesitter` just put out a new release earlier in April. We just need to tick up some versions at some point.
